name: Rust

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup | Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Lint
        run: cargo clippy
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: miri
      - name: Test
        env:
          MIRIFLAGS: "-Zmiri-backtrace=full -Zmiri-disable-stacked-borrows -Zmiri-tree-borrows"
        run: cargo miri test --all-features
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: rustfmt
      - name: Commit formatted files
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.TOKEN }}
